"""Generate src/ext_table.h (file extension -> ARC type hash) from re6arc (tools/re6arc).

usage: python tools/gen_ext_table.py

re6arc names every type with the game's own extension (the one sResource appends when it loads a loose file,
extracted from BH6.exe); where several classes share an extension, the one that occurs in arcs wins.
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from re6arc import arc  # noqa: E402

out = ["// generated by tools/gen_ext_table.py from re6arc - do not edit",
       "// the game's own extensions (BH6.exe, resource class vtable +0x18)",
       "#pragma once", "#include <cstdint>", "",
       "struct ExtHash { const wchar_t* ext; uint32_t hash; };", "",
       "static const ExtHash kExtTable[] = {"]
for e, h in sorted(arc.EXT_TO_HASH.items()):
    out.append(f'    {{L"{e}", 0x{h:08X}u}},  // {arc.class_of(h)}')
out += ["};", ""]
(HERE.parent / "src" / "ext_table.h").write_text("\n".join(out), encoding="utf-8")
print(f"{len(arc.EXT_TO_HASH)} extensions written")
